language: node_js

node_js: 10.16.3

sudo: enabled

if: (type = push AND branch = master) OR (type = pull_request)

install: npm ci

env:
  - COMMAND=lint NAME="Lint tests"
  - COMMAND=build NAME="Build project"

script:
  - npm run $COMMAND
